# Generated by Django 4.0.2 on 2022-03-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='origin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
