# Generated by Django 4.0.2 on 2022-03-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.ManyToManyField(to='viewer.Star'),
        ),
    ]
