# Generated by Django 4.0.2 on 2022-03-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_movie_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.ManyToManyField(blank=True, to='viewer.Star'),
        ),
    ]
