# Generated by Django 4.0.2 on 2022-03-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Russian', 'Russian'), ('Estonian', 'Estonian')], max_length=20, null=True),
        ),
    ]
