# Generated by Django 4.0.2 on 2022-04-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0017_alter_profile_user_alter_rate_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_movies',
            field=models.ManyToManyField(to='viewer.Movie'),
        ),
    ]
